// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/ehazlett/circuit/api/circuit/v1/cluster.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type NodeInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7bb2fc0c6485ec0, []int{0}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type NodesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodesRequest) Reset()         { *m = NodesRequest{} }
func (m *NodesRequest) String() string { return proto.CompactTextString(m) }
func (*NodesRequest) ProtoMessage()    {}
func (*NodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7bb2fc0c6485ec0, []int{1}
}
func (m *NodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesRequest.Unmarshal(m, b)
}
func (m *NodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesRequest.Marshal(b, m, deterministic)
}
func (m *NodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesRequest.Merge(m, src)
}
func (m *NodesRequest) XXX_Size() int {
	return xxx_messageInfo_NodesRequest.Size(m)
}
func (m *NodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodesRequest proto.InternalMessageInfo

type NodesResponse struct {
	Nodes                []*NodeInfo `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NodesResponse) Reset()         { *m = NodesResponse{} }
func (m *NodesResponse) String() string { return proto.CompactTextString(m) }
func (*NodesResponse) ProtoMessage()    {}
func (*NodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7bb2fc0c6485ec0, []int{2}
}
func (m *NodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesResponse.Unmarshal(m, b)
}
func (m *NodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesResponse.Marshal(b, m, deterministic)
}
func (m *NodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesResponse.Merge(m, src)
}
func (m *NodesResponse) XXX_Size() int {
	return xxx_messageInfo_NodesResponse.Size(m)
}
func (m *NodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodesResponse proto.InternalMessageInfo

func (m *NodesResponse) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// ClusterRequest is used to send requests through the cluster
type ClusterRequest struct {
	Channel              string     `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Request              *types.Any `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ClusterRequest) Reset()         { *m = ClusterRequest{} }
func (m *ClusterRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterRequest) ProtoMessage()    {}
func (*ClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7bb2fc0c6485ec0, []int{3}
}
func (m *ClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterRequest.Unmarshal(m, b)
}
func (m *ClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterRequest.Marshal(b, m, deterministic)
}
func (m *ClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterRequest.Merge(m, src)
}
func (m *ClusterRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterRequest.Size(m)
}
func (m *ClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterRequest proto.InternalMessageInfo

func (m *ClusterRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ClusterRequest) GetRequest() *types.Any {
	if m != nil {
		return m.Request
	}
	return nil
}

// OpComplete is used to signal completed response
type OpComplete struct {
	Node                 string   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpComplete) Reset()         { *m = OpComplete{} }
func (m *OpComplete) String() string { return proto.CompactTextString(m) }
func (*OpComplete) ProtoMessage()    {}
func (*OpComplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7bb2fc0c6485ec0, []int{4}
}
func (m *OpComplete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpComplete.Unmarshal(m, b)
}
func (m *OpComplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpComplete.Marshal(b, m, deterministic)
}
func (m *OpComplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpComplete.Merge(m, src)
}
func (m *OpComplete) XXX_Size() int {
	return xxx_messageInfo_OpComplete.Size(m)
}
func (m *OpComplete) XXX_DiscardUnknown() {
	xxx_messageInfo_OpComplete.DiscardUnknown(m)
}

var xxx_messageInfo_OpComplete proto.InternalMessageInfo

func (m *OpComplete) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type ContainerIPQuery struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Container            string   `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerIPQuery) Reset()         { *m = ContainerIPQuery{} }
func (m *ContainerIPQuery) String() string { return proto.CompactTextString(m) }
func (*ContainerIPQuery) ProtoMessage()    {}
func (*ContainerIPQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7bb2fc0c6485ec0, []int{5}
}
func (m *ContainerIPQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerIPQuery.Unmarshal(m, b)
}
func (m *ContainerIPQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerIPQuery.Marshal(b, m, deterministic)
}
func (m *ContainerIPQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerIPQuery.Merge(m, src)
}
func (m *ContainerIPQuery) XXX_Size() int {
	return xxx_messageInfo_ContainerIPQuery.Size(m)
}
func (m *ContainerIPQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerIPQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerIPQuery proto.InternalMessageInfo

func (m *ContainerIPQuery) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ContainerIPQuery) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeInfo)(nil), "io.circuit.v1.NodeInfo")
	proto.RegisterType((*NodesRequest)(nil), "io.circuit.v1.NodesRequest")
	proto.RegisterType((*NodesResponse)(nil), "io.circuit.v1.NodesResponse")
	proto.RegisterType((*ClusterRequest)(nil), "io.circuit.v1.ClusterRequest")
	proto.RegisterType((*OpComplete)(nil), "io.circuit.v1.OpComplete")
	proto.RegisterType((*ContainerIPQuery)(nil), "io.circuit.v1.ContainerIPQuery")
}

func init() {
	proto.RegisterFile("github.com/ehazlett/circuit/api/circuit/v1/cluster.proto", fileDescriptor_b7bb2fc0c6485ec0)
}

var fileDescriptor_b7bb2fc0c6485ec0 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x6b, 0xc2, 0x40,
	0x10, 0xc5, 0xb1, 0xad, 0xb5, 0x8e, 0x55, 0xca, 0x52, 0x68, 0x6a, 0x3d, 0x48, 0x4e, 0x5e, 0xdc,
	0x45, 0x7b, 0x11, 0x0a, 0x85, 0xea, 0xc9, 0x42, 0xbf, 0x72, 0xf4, 0x16, 0xe3, 0xa8, 0x0b, 0x71,
	0x27, 0xdd, 0x6c, 0x02, 0xf6, 0xaf, 0x2f, 0xd9, 0x64, 0x2b, 0x05, 0x29, 0xbd, 0xcd, 0xc7, 0x4b,
	0xe6, 0xfd, 0x1e, 0x0b, 0x93, 0x8d, 0x34, 0xdb, 0x6c, 0xc9, 0x23, 0xda, 0x09, 0xdc, 0x86, 0x5f,
	0x31, 0x1a, 0x23, 0x22, 0xa9, 0xa3, 0x4c, 0x1a, 0x11, 0x26, 0xf2, 0xa7, 0xce, 0x47, 0x22, 0x8a,
	0xb3, 0xd4, 0xa0, 0xe6, 0x89, 0x26, 0x43, 0xac, 0x2d, 0x89, 0x57, 0x4b, 0x9e, 0x8f, 0xba, 0xb7,
	0x1b, 0xa2, 0x4d, 0x8c, 0xc2, 0x2e, 0x97, 0xd9, 0x5a, 0x84, 0x6a, 0x5f, 0x2a, 0xfd, 0x09, 0x5c,
	0xbc, 0xd2, 0x0a, 0xe7, 0x6a, 0x4d, 0x8c, 0xc1, 0x99, 0x0a, 0x77, 0xe8, 0xd5, 0xfa, 0xb5, 0x41,
	0x33, 0xb0, 0x35, 0xf3, 0xa0, 0x91, 0xa3, 0x4e, 0x25, 0x29, 0xef, 0xc4, 0x8e, 0x5d, 0xeb, 0x77,
	0xe0, 0xb2, 0xf8, 0x32, 0x0d, 0xf0, 0x33, 0xc3, 0xd4, 0xf8, 0x8f, 0xd0, 0xae, 0xfa, 0x34, 0x21,
	0x95, 0x22, 0x1b, 0x42, 0x5d, 0x15, 0x03, 0xaf, 0xd6, 0x3f, 0x1d, 0xb4, 0xc6, 0x37, 0xfc, 0x97,
	0x29, 0xee, 0xce, 0x06, 0xa5, 0xca, 0x5f, 0x40, 0x67, 0x56, 0x42, 0x54, 0x7f, 0x2c, 0x6e, 0x47,
	0xdb, 0x50, 0x29, 0x8c, 0x2b, 0x4b, 0xae, 0x65, 0x1c, 0x1a, 0xba, 0x14, 0x59, 0x57, 0xad, 0xf1,
	0x35, 0x2f, 0x11, 0xb9, 0x43, 0xe4, 0x4f, 0x6a, 0x1f, 0x38, 0x91, 0xdf, 0x07, 0x78, 0x4b, 0x66,
	0xb4, 0x4b, 0x62, 0x34, 0x68, 0x39, 0x69, 0x75, 0xe0, 0xa4, 0x15, 0xfa, 0xcf, 0x70, 0x35, 0x23,
	0x65, 0x42, 0xa9, 0x50, 0xcf, 0xdf, 0x3f, 0x32, 0xd4, 0xfb, 0x3f, 0xee, 0xf7, 0xa0, 0x19, 0x39,
	0x75, 0x95, 0xcb, 0x61, 0x30, 0x7e, 0x81, 0x46, 0x45, 0xc2, 0xa6, 0x50, 0xb7, 0xa1, 0xb0, 0xbb,
	0x23, 0xf4, 0x2e, 0xba, 0x6e, 0xef, 0xf8, 0xb2, 0xcc, 0x71, 0x2a, 0x16, 0xc3, 0xff, 0x3f, 0x84,
	0x87, 0x7c, 0xb4, 0x3c, 0xb7, 0x21, 0xdc, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x72, 0xa7, 0xd1,
	0xff, 0x40, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterClient interface {
	Nodes(ctx context.Context, in *NodesRequest, opts ...grpc.CallOption) (*NodesResponse, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Nodes(ctx context.Context, in *NodesRequest, opts ...grpc.CallOption) (*NodesResponse, error) {
	out := new(NodesResponse)
	err := c.cc.Invoke(ctx, "/io.circuit.v1.Cluster/Nodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServer is the server API for Cluster service.
type ClusterServer interface {
	Nodes(context.Context, *NodesRequest) (*NodesResponse, error)
}

// UnimplementedClusterServer can be embedded to have forward compatible implementations.
type UnimplementedClusterServer struct {
}

func (*UnimplementedClusterServer) Nodes(ctx context.Context, req *NodesRequest) (*NodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Nodes not implemented")
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Nodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Nodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.circuit.v1.Cluster/Nodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Nodes(ctx, req.(*NodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.circuit.v1.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Nodes",
			Handler:    _Cluster_Nodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/ehazlett/circuit/api/circuit/v1/cluster.proto",
}
